name: C CI Pipeline

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        standard: [c89, c99, c11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        env: 
          CC: ${{ matrix.compiler }}
        run: CFLAGS="$(CFLAGS) -std=${{ matrix.standard }}" make
